#! /usr/bin/env bash

FONT_URL=https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/JetBrainsMono.zip
oh_my_tmux_path=~/oh-my-tmux

install-configs() {
    echo "Installing configs..."

    stow -vt ~ \
        alacritty \
        bat \
        i3 \
        kitty \
        mpv \
        neofetch \
        nvim \
        qtile \
        ranger \
        rofi \
        shell \
        sxhkd \
        tmux

    echo "Installing mpv shaders..."

    cp -vr _data/shaders ~/.config/mpv/

    echo "Installing Oh-my-tmux plugin..."

    git clone https://github.com/gpakosz/.tmux.git "$oh_my_tmux_path"
    ln -s -f "$oh_my_tmux_path"/.tmux.conf ~/.tmux.conf

    echo "Installing NNN plugins..."
    sh -c "$(curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs)"
}

install-fonts() {
    echo "Installing fonts..."

    mkdir -p ~/.local/share/fonts
    cd ~/.local/share/fonts/ || exit

    curl -L "$FONT_URL" >JetBrainsMono.zip
    unzip JetBrainsMono.zip -d JetBrainsMono
    fc-cache -f -v
    rm JetBrainsMono.zip
}

adopt-config() {
    program=$1
    echo "Adopting config from [$program]"

    mkdir -p "$program"/.config/"$program"
    stow --adopt --verbose --target ~ "$program"
}

"$@"
