#! /usr/bin/env bash

FONT_URL=https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/JetBrainsMono.zip
ZSH_PLUGINS_PATH=~/.local/share/zsh-plugins/
oh_my_tmux_path=~/oh-my-tmux

pipe-error() {
    RED='\033[0;31m'
    NC='\033[0m' # No Color
    while read -r line; do
        icon=$([[ $line != "" ]] && echo " " || echo "")
        printf "\t${RED}$icon%s${NC}\n" "$line"
    done
}

tabbed() {
    while read -r line; do printf "\t%s\n" "$line"; done
}

exec 2> >(pipe-error)

echo-header() {
    lolcat -f
}

install-config() {
    conf=$1
    stow -vt ~ "$conf"
}

install-configs() {
    echo "Installing configs..." | echo-header
    stow -vt ~ \
        alacritty \
        bat \
        i3 \
        kitty \
        mpv \
        neofetch \
        nvim \
        qtile \
        ranger \
        rofi \
        starship \
        sxhkd \
        tmux \
        zsh
}

install-dependency() {
    command="$1"
    echo "--- Installing [$command] ---" | echo-header
    {
        echo ""
        eval "install-$command"
        echo ""
        echo ""
    } | tabbed
}

install-dependencies() {
    install-dependency apt-dependencies
    install-dependency mpv-shaders
    install-dependency oh-my-tmux
    install-dependency nnn-plugins
    install-dependency zsh
    install-dependency zsh-plugins
    install-dependency fzf
}

install-apt-dependencies() {
    sudo apt install -y \
        exa \
        nnn \
        ranger \
        tmux \
        stow \
        lolcat
}

install-pacman-dependencies() {
    sudo pacman -S \
        alacritty \
        bat \
        exa \
        lolcat \
        mpv \
        nnn \
        ranger \
        starship \
        stow \
        tmux
}

install-mpv-shaders() {
    cp -vr _data/shaders ~/.config/mpv/
}

install-oh-my-tmux() {
    git clone https://github.com/gpakosz/.tmux.git "$oh_my_tmux_path" && ln -s -f "$oh_my_tmux_path"/.tmux.conf ~/.tmux.conf
}

install-nnn-plugins() {
    sh -c "$(curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs)"
}

install-fzf() {
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install --no-key-bindings --no-completion --no-update-rc
}

install-zsh() {
    ZSH_TMP_DIR=/tmp/zsh-latest
    git clone git://git.code.sf.net/p/zsh/code $ZSH_TMP_DIR && cd $ZSH_TMP_DIR && ./Util/preconfig && ./configure && make -j4 && sudo make install
}

install-zsh-plugins() {
    mkdir -p $ZSH_PLUGINS_PATH
    cd $ZSH_PLUGINS_PATH || return 1
    git clone https://github.com/Aloxaf/fzf-tab
    git clone https://github.com/zsh-users/zsh-autosuggestions
    git clone https://github.com/zsh-users/zsh-completions.git
    # git clone https://github.com/zsh-users/zsh-syntax-highlighting
    git clone https://github.com/zdharma-continuum/fast-syntax-highlighting
    git clone https://github.com/zsh-users/zsh-history-substring-search
    git clone https://github.com/agkozak/zsh-z.git
    git clone https://github.com/marzocchi/zsh-notify.git
}

install-fonts() {
    echo "Installing fonts..." | echo-header

    mkdir -p ~/.local/share/fonts
    cd ~/.local/share/fonts/ || exit

    curl -L "$FONT_URL" >JetBrainsMono.zip
    unzip JetBrainsMono.zip -d JetBrainsMono
    fc-cache -f -v
    rm JetBrainsMono.zip
}

adopt-config() {
    program=$1
    echo "Adopting config from [$program]"

    mkdir -p "$program"/.config/"$program"
    stow --adopt --verbose --target ~ "$program"
}

"$@"
