#!/usr/bin/env bash

# history
alias h="history -i"

# fail2ban client
alias f2b="sudo fail2ban-client"

# lastpass
alias lps="lpass-select"

# neovim
alias vf='fzf | xargs "$EDITOR"'
alias v="nvim"

# zsh
alias zzh="zsh-show-keybindings"

# youtube-dl
alias yta="youtube-dl --extract-audio --audio-format mp3"
alias ytv="youtube-dl"

# mount
alias mntp="mkdir ~/Phone && go-mtpfs ~/Phone &"
alias umntp="fusermount -u ~/Phone"

# exa ls
# general use
alias ls='exa'                                                          # ls
alias l='exa -lbF --git'                                                # list, size, type, git
alias ll='exa -lbGF --git'                                             # long list
alias llm='exa -lbGd --git --sort=modified'                            # long list, modified date sort
alias la='exa -lbhHigUmuSa --time-style=long-iso --git --color-scale'  # all list
alias lx='exa -lbhHigUmuSa@ --time-style=long-iso --git --color-scale' # all + extended list

# specialty views
alias lS='exa -1'                                                              # one column, just names
alias lt='exa --tree --level=2'                                         # tree

# gpt as a translator
alias eng="gpt translate to english the input: "
alias spa="gpt translate to spanish the input: "

# git
alias gs='git status'
alias gst='git status'
alias ga='git add'
alias gp='git push'
alias gpo='git push origin'
alias gtd='git tag --delete'
alias gtdr='git tag --delete origin'
alias gr='git branch -r'
alias gplo='git pull origin'
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gl='git pull'
alias gr='git remote'
alias grs='git remote show'
alias glo='git log --pretty="oneline"'
alias glol='git log --graph --oneline --decorate'

# apt
alias agud="sudo apt update && sudo apt dist-upgrade"
alias aguu="sudo apt update && sudo apt upgrade"
alias agar="sudo apt autoremove"
alias agi="sudo apt install"
alias agr="sudo apt remove"

# docker & docker-compose
alias dcps="docker-compose ps"
alias dce="docker-compose exec"
alias dcl="docker-compose logs"
alias dclf="docker-compose logs -f"
alias dcrestart="docker-compose restart"
alias dcup="docker-compose up -d"
alias dcupb="docker-compose up -d --build"
alias dcdn="docker-compose down"
alias dcstop="docker-compose stop"
alias dcstart="docker-compose start"
