#!/usr/bin/env bash

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000
export HIST_STAMPS="yyyy-mm-dd"

export EDITOR=nvim
export VISUAL=nvim
export PAGER=bat
export BAT_PAGER=less

# nnn configs
export NNN_PLUG='o:fzopen;m:nmount;x:!chmod +x $nnn;p:preview-tui'
export NNN_FIFO=/tmp/nnn.fifo
export NNN_OPENER=nuke
export NNN_OPTS=c

# starship path
export STARSHIP_CONFIG=$XDG_CONFIG_HOME/starship/starship.toml

# paths
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.fzf/bin/"
export PATH="$PATH:$XDG_CONFIG_HOME/nnn/plugins"
export PATH="$PATH:$(go env GOPATH)/bin"

# Man pages on nvim
export MANPAGER='nvim +Man!'

# fzf
export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git"'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

FZF_COLORS="bg+:-1,fg:gray,fg+:white,border:black,spinner:0,hl:yellow,header:blue,info:green,pointer:red,marker:blue,prompt:gray,hl+:red"

export FZF_DEFAULT_OPTS="--height 60% \
    --layout reverse-list \
    --color '$FZF_COLORS' \
    --prompt '∷ ' \
    --pointer ▶ \
    --marker ⇒"
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -n 10'"

# vi: ft=sh
