#!/usr/bin/env bash
# shellcheck disable=1090

# Bash completion init
autoload -U +X bashcompinit && bashcompinit

# Zsh completion init
autoload -U +X compinit && compinit

# Aliases
source ~/.config/zsh/aliases

# Keybinds
source ~/.config/zsh/keybind

# Zsh plugins
source ~/.local/share/zsh-plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
source ~/.local/share/zsh-plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.local/share/zsh-plugins/fzf-tab/fzf-tab.plugin.zsh
source ~/.local/share/zsh-plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source ~/.local/share/zsh-plugins/zsh-z/zsh-z.plugin.zsh
fpath=(~/.local/share/zsh-plugins/zsh-completions/src $fpath)

reload() {
    if [[ ! -f $ZDOTDIR/.zcompdump ]]; then
        echo "No file found"
        return 1
    fi

    rm "$ZDOTDIR"/.zcompdump
    rm -rf "$XDG_CACHE_HOME/zsh/.zcompcache"

    echo "zcompdump and zcompcache removed!"
    exec zsh
}

config() {
    $EDITOR $ZDOTDIR/.zshrc
}

# Zsh zstyle configs
zstyle ':completion:*' verbose yes

# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false

# For the command cd, chdir and pushd, you can use a hyphen - for completing for an option
zstyle ':completion:*' complete-options true

# set descriptions format to enable group support
zstyle ':completion:*:descriptions' format '[%d]'

# switch group using `,` and `.`
zstyle ':fzf-tab:*' switch-group ',' '.'
zstyle ':fzf-tab:*' show-group full

# this is an example
zstyle ':fzf-tab:complete:(\\|)run-help:*' fzf-preview 'run-help $word'
zstyle ':fzf-tab:complete:(\\|*/|)man:*' fzf-preview 'man $word'

# preview directory's content with exa when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls -1 --color=always $realpath' # remember to use single quote here!!!
# zstyle ':fzf-tab:complete:*:*' fzf-preview 'bat --color=always ${(Q)realpath}'

# Caching the Completion
# Using a cache for the completion can speed up some commands, like apt for example. Let’s add the following in our file to enable it:
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME/zsh/.zcompcache"

# Case insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# vi: ft=sh
