#!/usr/bin/env bash
# shellcheck disable=1090,1091

declare -A CONFIG_FILES
CONFIG_FILES[zshenv]=~/.zshenv
CONFIG_FILES[zshrc]="$ZDOTDIR"/.zshrc
CONFIG_FILES[exports]=$ZDOTDIR/exports
CONFIG_FILES[zshconf]=$ZDOTDIR/zshconf
CONFIG_FILES[keybind]=$ZDOTDIR/keybind

# Aliases
source ~/.config/zsh/aliases

# Keybinds
source ~/.config/zsh/keybind

# FZF default key-bindings and completions
source "$(dirname "$FZF_BASE")"/../shell/key-bindings.zsh
source "$(dirname "$FZF_BASE")"/../shell/completion.zsh

# Zsh plugins
source ~/.local/share/zsh-plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
source ~/.local/share/zsh-plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.local/share/zsh-plugins/fzf-tab/fzf-tab.plugin.zsh
source ~/.local/share/zsh-plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source ~/.local/share/zsh-plugins/zsh-z/zsh-z.plugin.zsh

# shellcheck disable=2206
fpath=(~/.local/share/zsh-plugins/zsh-completions/src $fpath)
# shellcheck disable=2206,2128
fpath=($ZDOTDIR/custom-completions $fpath)

# Bash completion init
autoload -U bashcompinit && bashcompinit

# Zsh completion init (IMPORTANT: this must go after fpath updates)
# On slow systems, checking the cached .zcompdump file to see if it must be
# regenerated adds a noticable delay to zsh startup.  This little hack restricts
# it to once a day.  It should be pasted into your own completion file.
# autoload -Uz compinit

for dump in ~/.zcompdump(N.mh+24); do
    compinit
done
# The check performed to see if there are new functions can be omitted by giving the option -C. In this case the dump file will only be created if there isn't one already.
compinit -C


# reload and zconf functions
reload() {
    if [[ ! -f $ZDOTDIR/.zcompdump ]]; then
        echo "No file found"
        return 1
    fi

    rm "$ZDOTDIR"/.zcompdump && echo "zcompdump removed."
    rm -rf "$XDG_CACHE_HOME/zsh/.zcompcache" && echo "zcompcache removed."
    exec zsh
}

zconf() {
    $EDITOR "${CONFIG_FILES[$1]}"
}

# _complete - This is the main completer we need to use for our completion.
# _approximate - This one is similar to _complete, except that it will try to correct what you’ve typed already (the context) if no match is found.
# _expand_alias - Expand an alias you’ve typed. It needs to be declared before _complete.
# _extensions - Complete the glob *. with the possible file extensions.
zstyle ':completion:*' completer _expand_alias _extensions _complete _approximate

zstyle ':completion:*' verbose yes

# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false

# For the command cd, chdir and pushd, you can use a hyphen - for completing for an option
zstyle ':completion:*' complete-options true

# set descriptions format to enable group support
zstyle ':completion:*:descriptions' format '[%d]'

# switch group using `,` and `.`
zstyle ':fzf-tab:*' switch-group ',' '.'
zstyle ':fzf-tab:*' show-group full

# this is an example
zstyle ':fzf-tab:complete:(\\|)run-help:*' fzf-preview 'run-help $word'
zstyle ':fzf-tab:complete:(\\|*/|)man:*' fzf-preview 'man $word'

# preview directory's content with exa when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls -1 --color=always $realpath' # remember to use single quote here!!!
# zstyle ':fzf-tab:complete:*:*' fzf-preview 'bat --color=always ${(Q)realpath}'

# Caching the Completion
# Using a cache for the completion can speed up some commands, like apt for example. Let’s add the following in our file to enable it:
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME/zsh/.zcompcache"

# Case insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
# vi: ft=sh
