general.live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 100

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.cursor]
cursor = "#ffffff"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#000000"
foreground = "#ebdbb2"

[cursor]
blink_interval = 200
blink_timeout = 255
thickness = 0.1

[cursor.style]
blinking = "Always"
shape = "Beam"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
command = { program = "alacritty", args = [
    "msg",
    "config",
    "window.opacity=0.85",
] }
key = "T"
mods = "Super"

[[keyboard.bindings]]
command = { program = "alacritty", args = [
    "msg",
    "config",
    "window.opacity=1",
] }
key = "I"
mods = "Super"

[mouse]
hide_when_typing = true

[scrolling]
multiplier = 10

[window]
decorations = "none"
decorations_theme_variant = "Dark"
dynamic_padding = true
dynamic_title = true
opacity = 0.85
blur = true
startup_mode = "Fullscreen"

[window.dimensions]
columns = 160
lines = 40

[window.padding]
x = 20
y = 20
