#! /usr/bin/env bash

MESSAGE="$1"
CHANNEL="#general"
USERNAME=""
ICON=":computer:"

if [ ! $LOCAL_SLACK_WEBHOOK ]; then
    echo "LOCAL_SLACK_WEBHOOK environment variable is not defined"
    exit 1
fi

options=$(getopt --long channel:,username:,icon: --options "" -- "$@")
#echo "$options"
eval set -- "$options"

while true; do
    case $1 in
        --icon)
            ICON="$2"
            shift 2
            ;;
        --username)
            USERNAME="$2"
            shift 2
            ;;
        --channel)
            CHANNEL="$2"
            shift 2
            ;;
        --)
            MESSAGE="${*:2}"
            shift
            break
            ;;
        *)
            echo "Internal error!"
            exit 1
            ;;
    esac
done

#echo "CHANNEL:$CHANNEL"
#echo "MESSAGE:$MESSAGE"
#echo "ICON:$ICON"
#echo "USERNAME:$USERNAME"

json-init() {
    TMP_FILE=$(mktemp)
    echo "{}">"$TMP_FILE"
}

json-set() {
    local key="$1"
    local value=${*:2}

    content=$(jq ".$key = \"$value\"" "$TMP_FILE") && echo "$content">"$TMP_FILE"
}

json-destroy() {
    rm "$TMP_FILE"
}

FROM="$(whoami)@$(hostname)"
MESSAGE="$MESSAGE\n\nEnviado desde $FROM"

json-init
json-set channel "$CHANNEL"
json-set username "${USERNAME:-$FROM}"
json-set text "$MESSAGE"
json-set icon_emoji "$ICON"

curl -X POST --silent --data-urlencode "payload=$(cat "$TMP_FILE")" "$LOCAL_SLACK_WEBHOOK"

json-destroy
